const API_PARAMS = {
  TIME_SERIES_DAILY: "TIME_SERIES_DAILY",
  OVERVIEW: "OVERVIEW",
  GLOBAL_QUOTE: "GLOBAL_QUOTE",
};

const MEDIA_SIZES = {
  MOBILE: "720",
};

export { API_PARAMS, MEDIA_SIZES };
